### PR TITLE
fix: use full response to check in tests

### LINKED ISSUE #138: response_contains does not check the full response
The [ftw YAML format spec](https://github.com/coreruleset/ftw/blob/main/docs/YAMLFormat.md#response_contains) says:

> ### response_contains
>
> **Description:** Checks the entire response against the regular expression provided.

However, `go-ftw` only matches against the body of the response. This causes problems for tests that want to check that a a specific header is set by the firewall, or want to check responses that have no body.

### PR DESCRIPTION
**Pull request by fzipi**
Now tests will check against the full response (status, headers, body)

Fixes #138.

### CODE REVIEW

File: ftwhttp/response_test.go [hunk 1]
```diff
@@ -126,3 +146,28 @@ func TestResponseWithCookies(t *testing.T) {
...
+	err = client.NewConnection(*d)
+
+	assert.NoError(t, err)
+
+	response, err := client.Do(*req)
+
+	assert.NoError(t, err)
+
+	assert.Contains(t, response.GetBodyAsString(), "User-Agent=[Go Tests]")
+	assert.NotContains(t, response.GetBodyAsString(), "X-Powered-By: [go-ftw]\n")
```
Comment (theseion) [inline ftwhttp/response_test.go:170]: Shouldn't this be the same value as on the next line, where you check the full response?

```suggestion
	assert.NotContains(t, response.GetBodyAsString(), "X-Powered-By: go-ftw")
```

File: runner/run.go
Comment (theseion) [inline runner/run.go:1]: Do you want to add an option to check response body only later? Otherwise, `GetBodyAsString` isn't of much use now.

**Review by theseion — CHANGES_REQUESTED** [review]

File: ftwhttp/response_test.go (hunk 1 above)
Comment (fzipi) [reply ftwhttp/response_test.go]: Removed this and we are checking the full response.

**Review by theseion — APPROVED** [review]
